# 训练配置
train:
  batch_size: 64
  epochs: 10
  learning_rate: 0.001
  optimizer: Adam
  loss_function: CrossEntropyLoss

# 设备配置
device:
  use_cuda: true

# 数据配置
data:
  dataset: FashionMNIST
  data_dir: ./data
  download: true

